platform: bricks-dev
document_type: cookie
language: it_IT

version: v005
drafted_on: 16-11-2025
effective_from:

author:
reviewed_by:

github_release_tag: bricks-dev_cookie_16-11-2025_it_IT_v005
github_release_asset: bricks-dev_cookie_16-11-2025_it_IT_v005.pdf

notes:
