platform: sample-app
document_type: terms
language: it_IT

version: v001
drafted_on: 20-05-2024
effective_from:

author:
reviewed_by:

github_release_tag: sample-app_terms_20-05-2024_it_IT_v001
github_release_asset: sample-app_terms_20-05-2024_it_IT_v001.pdf

notes:
