platform: mydewetra-italy
document_type: terms
language: it_IT

version: v008
drafted_on: 19-01-2026
effective_from:

author:
reviewed_by:

github_release_tag: mydewetra-italy_terms_19-01-2026_it_IT_v008
github_release_asset: mydewetra-italy_terms_19-01-2026_it_IT_v008.pdf

notes:
