platform: mydewetra-italy
document_type: terms
language: it_IT

version: v001
drafted_on: 05-02-2026
effective_from:

author:
reviewed_by:

github_release_tag: mydewetra-italy_terms_05-02-2026_it_IT_v001
github_release_asset: mydewetra-italy_terms_05-02-2026_it_IT_v001.pdf

notes:
