platform: bricks-dev
document_type: cookie
language: it_IT

version: v004
drafted_on: 14-11-2025
effective_from:

author:
reviewed_by:

github_release_tag: bricks-dev_cookie_14-11-2025_it_IT_v004
github_release_asset: bricks-dev_cookie_14-11-2025_it_IT_v004.pdf

notes:
